application: modular-bot-537
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
#- url: /
#  script: wtd.application

- url: /(.*\.html)
  mime_type: text/html
  static_files: app/\1
  upload: app/(.*\.html)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: app/\1
  upload: app/(.*\.js)

- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: app/\1
  upload: app/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /
  static_files: app/views/main.html
  upload: app/views/main.html

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]